Add qrcode generator and change exe project to library project
blazorstudy/check-in-manager pull request #6
Opened 2023-09-11 14:19 UTC by level120

QR 코드 생성기 추가하고 Cups 프린터 프로젝트를 라이브러로 변경했습니다.

2023-09-11 14:20 UTC, level120 commented on src/CheckInManager.QRGenerator/Services/QRGeneratorService.cs
> +        return CreateImage(ImageType.Png, content, DefaultQRSize);
샘플로 `svg`, `jpeg`, `png` 이렇게 3개 뽑아봤는데 `png`가 용량이 제일 적게 먹어서 우리 모델의 기본값으로 지정했어요.

2023-09-11 14:25 UTC, level120 commented on src/CheckInManager.QRGenerator/Services/QRGeneratorService.cs
> +        return CreateImage(ImageType.Png, content, DefaultQRSize);
### 샘플 SVG
![2023-09-11 10_51_30_53689164](https://github.com/blazorstudy/check-in-manager/assets/10791961/22f8ce49-17b8-4c36-bcf3-ac99c4e96fa9)

### 샘플 PNG
![2023-09-11 10_51_31_53689699](https://github.com/blazorstudy/check-in-manager/assets/10791961/0b150d4e-2f24-4ef4-bb30-0ea11eff2298)

### 샘플 JPEG
![2023-09-11 10_51_31_53689706](https://github.com/blazorstudy/check-in-manager/assets/10791961/1fabea88-98c8-4485-8106-6ec51deaca78)

2023-09-11 15:56 UTC, level120 commented on src/CheckInManager.Api.Printer/Triggers/PrintDocument.cs
> +        _printerService.Print(model);
프린터 출력 확인 완료!

2023-09-11 15:57 UTC, level120 commented on src/CheckInManager.Api.QRGenerator/Triggers/GenerateQRCode.cs
>          return response;
애저 펑션으로 QR 그림 반환 확인 완료!

2023-09-12 01:15 UTC, justinyoo requested changes
오우 QR 코드 라이브러리 쪽 코멘트 좀 남겨뒀습니당.

그나저나, 지금은 시간이 없으니 테스트 코드들은 나중에 만드는 걸로 할까요?

2023-09-12 01:15 UTC, justinyoo commented on src/CheckInManager.QRGenerator/Services/QRGeneratorService.cs
> +    public ReadOnlySpan<byte> CreateFrom(MeetUpNameTagModel model)
요기에 옵셔널 파라미터로 `Size` 값을 `DefaultQRSize`로 해 주면 어때요? 그러면 호출하는 쪽에서 사이즈도 인젝션할 수 있을 듯?

2023-09-12 01:15 UTC, justinyoo commented on src/CheckInManager.QRGenerator/Services/QRGeneratorService.cs
> +    private readonly Size DefaultQRSize = new(800, 800);
이거 프라이빗 스타틱 필드로 사용하는 것 같은데 그러면 `private static Size defaultQRSize`가 더 맞을 것 같아요?

2023-09-12 01:15 UTC, justinyoo commented on src/CheckInManager.QRGenerator/Services/QRGeneratorService.cs
> +            throw new ArgumentException("Size couldn't empty.");
1. `Size couldn't be empty.`가 좀 더 정확할 듯 싶구요.
2. `IsEmpty` 플래그는 높이/너비 둘 다 0일때 true 반환하던데, 만약 하나만 0이면 어떻게 되나요?

2023-09-12 01:15 UTC, justinyoo commented on src/CheckInManager.QRGenerator/Services/QRGeneratorService.cs
> +        }
파라미터 순서를 따라가면 어떨까요? 이게 먼저, Size 체크가 그 다음

2023-09-12 01:15 UTC, justinyoo commented on src/CheckInManager.QRGenerator/Services/QRGeneratorService.cs
> +    public ReadOnlySpan<byte> CreateImage(ImageType imageType, string content, Size size, int margin = IQRGeneratorService.DefaultMargin)
사용자 입장에서는 사실 벡터든 비트맵이든 그냥 엔트리포인트 하나면 충분할 듯 해요. `Generate(ImageType imageType, string content, Size, int margin)`으로 호출하면 내부적으로 ImageType 값 확인해서 CreateVector 호출하든가 CreateImage 호출하든가 하는 형식이 되면 어떨까요?

2023-09-12 01:15 UTC, justinyoo commented on src/CheckInManager.QRGenerator/Services/QRGeneratorService.cs
> +    public ReadOnlySpan<byte> CreateFrom(MeetUpNameTagModel model)
아, 가만 보니 그러네... 이것도 `Generate<T>(T content, ImageType imageType = ImageType.Png, Size size = DefaultQRSize, int margin = QRGeneratorService.DefaultMargin)` 하는 식으로 해서 퉁칠 수 있지 않을까효?

그러면 그 안에서 `T`를 직렬화한 다음에 `Generate(string content, ImageType imageType, Size size, int margin)` 메소드로 보낸다거나 하면 될 듯?

2023-09-12 01:15 UTC, justinyoo commented on src/CheckInManager.QRGenerator/Services/Interfaces/IQRGeneratorService.cs
> +    protected const int DefaultMargin = 1;
이런 상수값은 보통 인터페이스에 넣나요, 클래스에 넣나요? 저는 구현쪽이라 생각해서 클래스에 넣는 편이긴 한데...

2023-09-12 10:12 UTC, level120 commented on src/CheckInManager.QRGenerator/Services/Interfaces/IQRGeneratorService.cs
> +    protected const int DefaultMargin = 1;
저도 그런 편인데.. 왜 그랬을까요,,,

2023-09-12 10:14 UTC, level120 commented on src/CheckInManager.QRGenerator/Services/QRGeneratorService.cs
> +            throw new ArgumentException("Size couldn't empty.");
둘 중 하나라도 0이거나 음수면 empty로 취급하도록 했어요,

2023-09-12 10:15 UTC, level120 commented on src/CheckInManager.QRGenerator/Services/QRGeneratorService.cs
> +    private readonly Size DefaultQRSize = new(800, 800);
질문! private 필드의 이름에는 언더바 안붙나요..?

2023-09-12 14:20 UTC, level120 commented
@justinyoo 님, 수정했습니다!
테스트 코드는 말씀주신대로 진행해야 할 것 같아요, 시간이 얼마 안남은지라.. 밋업쪽 프로젝트도 익혀야 하니..

2023-09-12 14:30 UTC, level120 commented on src/CheckInManager.CupsPrinter/Services/Interfaces/IPrinterService.cs
> +    Task PrintAsync(MeetUpNameTagModel model);
동시에 프린트 요청이 들어왔을 때 대기해야 하는 문제가 있어서 비동기로 변경했어요.

2023-09-12 15:56 UTC, justinyoo commented on src/CheckInManager.QRGenerator/Services/QRGeneratorService.cs
> +    private readonly Size DefaultQRSize = new(800, 800);
프라이빗 스타틱은 필드는 그냥 카멜케이스

2023-09-12 22:51 UTC, justinyoo requested changes
전 아주 좋습니다. 코멘트 몇 개만 달아뒀는데, 그것만 확인되면 바로 머지할 수 있겠네욥

2023-09-12 22:51 UTC, justinyoo commented on src/CheckInManager.Api.Printer/.gitignore
오우 이거는 원래 들어있던 거라 안 지우시는 게 좋겠어요

2023-09-12 22:51 UTC, justinyoo commented on src/CheckInManager.Api.QRGenerator/.gitignore
요것도 안 지우시면 좋겠습니당

2023-09-12 22:51 UTC, justinyoo commented on src/CheckInManager.CupsPrinter/Services/PrinterService.cs
> +    private static string CreateUniqueName()
메소드 이름이랑 내용이랑 다른것 같으니 `CreateUniqueFile` 정도면 어떨까요?

2023-09-12 22:51 UTC, justinyoo commented on src/CheckInManager.QRGenerator/Enums/ImageType.cs
> +    Svg
아예 .svg 지원을 뺀 것 같은데, 이것도 뺄까요?

2023-09-13 08:24 UTC, justinyoo approved these changes
고생하셨습니다!

2023-09-13 08:24 UTC, merged